<?php
/**
 * Main bootsrap file for the db api
 */

/**
 * Includes
 */

// Autoloader (using autogenerated composer autoloader)
if(file_exists('vendor/autoload.php')) {
	require 'vendor/autoload.php';
} else {
	echo "composer packages not installed";
	die();
}

// Include application config
require 'config/config.php';

/**
 * Debug
 */
if(DEBUG_MODE) {
	/**
	 * Error reporting
	 * Custom error reporting level for development. Useful to show every little problem.
	 */
	error_reporting(E_ALL);
	ini_set("display_errors", 1);
}
//Kint::enabled(DEBUG_MODE);

/**
 * Run App
 */

$app = new Slim\Slim(array(
    'mode' => 'production',
    'debug' => false
));

// set response content-type to JSON for all requests
$app->contentType('application/json; charset=utf-8');

// instantiate router (loads routes defined in config/routes.php)
new Router();

// run Slim
$app->run();